apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.squad | replace("group:default/", "") }}-${{ values.nome }}-${{ values.ambiente }}
  description: Bucket S3 provisionado pelo Atlas
  annotations:
    atlas.nuclea.com.br/recurso: s3
    atlas.nuclea.com.br/ambiente: ${{ values.ambiente }}
  tags:
    - aws
    - s3
    - ${{ values.ambiente }}
spec:
  type: s3
  owner: ${{ values.squad }}
  system: infraestrutura
