import type { Documento } from './types';

/**
 * Documentos de exemplo — os mesmos da tela HTML que esta substitui. Com o
 * catálogo, são as entidades com a anotação `backstage.io/techdocs-ref`
 * (ver `useDocs`).
 */
export const DOCUMENTOS: Documento[] = [
  {
    nome: 'pagamentos',
    ancora: 'system-pagamentos-docs',
    descricao: 'Tudo que movimenta dinheiro.',
    tipo: 'System',
    subtipo: 'system',
    dono: 'pagamentos',
    cicloDeVida: 'production',
    tags: ['dominio'],
    favorito: true,
  },
  {
    nome: 'payments-api',
    ancora: 'component-payments-api-docs',
    descricao: 'API de pagamentos: Pix, boleto e cartão.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'pagamentos',
    cicloDeVida: 'production',
    tags: ['java', 'pix', 'pagamentos'],
    favorito: true,
  },
  {
    nome: 'payments-api',
    ancora: 'api-payments-api-docs',
    descricao: 'Pagamentos: cobranças, estornos e consulta.',
    tipo: 'API',
    subtipo: 'openapi',
    dono: 'pagamentos',
    cicloDeVida: 'production',
    tags: ['rest', 'pix'],
    favorito: true,
  },
  {
    nome: 'SRO-4722',
    ancora: 'component-sro-4722-docs',
    descricao: 'Consulta de registros de operações.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'antifraude',
    cicloDeVida: 'production',
    tags: ['java', 'sro'],
    favorito: true,
  },
  {
    nome: 'antifraude-core',
    ancora: 'component-antifraude-core-docs',
    descricao: 'Motor de regras antifraude em tempo real.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'antifraude',
    cicloDeVida: 'production',
    tags: ['java', 'regras'],
    favorito: false,
  },
  {
    nome: 'antifraude-grpc',
    ancora: 'api-antifraude-grpc-docs',
    descricao: 'Avaliação síncrona de risco de transação.',
    tipo: 'API',
    subtipo: 'grpc',
    dono: 'antifraude',
    cicloDeVida: 'production',
    tags: ['grpc'],
    favorito: false,
  },
  {
    nome: 'atlas-agent',
    ancora: 'component-atlas-agent-docs',
    descricao: 'Agente do Atlas: chat sobre o catálogo.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'plataforma',
    cicloDeVida: 'experimental',
    tags: ['ia', 'node'],
    favorito: false,
  },
  {
    nome: 'atlas-agent-api',
    ancora: 'api-atlas-agent-api-docs',
    descricao: 'Chat do agente do Atlas.',
    tipo: 'API',
    subtipo: 'openapi',
    dono: 'plataforma',
    cicloDeVida: 'experimental',
    tags: ['ia'],
    favorito: false,
  },
  {
    nome: 'ledger-api',
    ancora: 'api-ledger-api-docs',
    descricao: 'Lançamentos e saldos do razão contábil.',
    tipo: 'API',
    subtipo: 'openapi',
    dono: 'pagamentos',
    cicloDeVida: 'production',
    tags: ['rest'],
    favorito: false,
  },
  {
    nome: 'ledger-service',
    ancora: 'component-ledger-service-docs',
    descricao: 'Razão contábil das transações.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'pagamentos',
    cicloDeVida: 'production',
    tags: ['kotlin', 'contabil'],
    favorito: false,
  },
  {
    nome: 'onboarding-web',
    ancora: 'component-onboarding-web-docs',
    descricao: 'Site de cadastro de novos clientes.',
    tipo: 'Component',
    subtipo: 'website',
    dono: 'onboarding',
    cicloDeVida: 'production',
    tags: ['react', 'web'],
    favorito: false,
  },
  {
    nome: 'portal',
    ancora: 'component-portal-docs',
    descricao: 'O próprio Atlas (Backstage).',
    tipo: 'Component',
    subtipo: 'website',
    dono: 'plataforma',
    cicloDeVida: 'production',
    tags: ['backstage', 'web'],
    favorito: false,
  },
  {
    nome: 'PREVCAP-2001',
    ancora: 'component-prevcap-2001-docs',
    descricao: 'Cálculo de contribuição da previdência.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'pagamentos',
    cicloDeVida: 'production',
    tags: ['java', 'previdencia'],
    favorito: false,
  },
  {
    nome: 'SRO-4760',
    ancora: 'component-sro-4760-docs',
    descricao: 'Cadastro de participantes do SRO.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'onboarding',
    cicloDeVida: 'production',
    tags: ['kotlin', 'sro'],
    favorito: false,
  },
  {
    nome: 'SRO-4790',
    ancora: 'component-sro-4790-docs',
    descricao: 'Documentação pública do SRO.',
    tipo: 'Component',
    subtipo: 'website',
    dono: 'plataforma',
    cicloDeVida: 'production',
    tags: ['web', 'docs'],
    favorito: false,
  },
  {
    nome: 'SRO-4821',
    ancora: 'component-sro-4821-docs',
    descricao: 'Motor de validação de registros.',
    tipo: 'Component',
    subtipo: 'service',
    dono: 'antifraude',
    cicloDeVida: 'production',
    tags: ['java', 'sro'],
    favorito: false,
  },
];
