import { makeStyles } from '@material-ui/core/styles';
import { atlasTokens } from '../../atlas/components/tokens';
import { cores, useAtlasStyles, verdeTexto } from '../shared/styles';

const { brand, radius } = atlasTokens;

/** O que só a Home tem: boas-vindas, blocos de números e os painéis. */
const useHomeStyles = makeStyles(theme => {
  const c = cores(theme);
  const escuro = theme.palette.type === 'dark';
  const verde = verdeTexto(theme);
  const sombra = escuro
    ? '0 1px 0 rgba(255,255,255,0.03) inset, 0 8px 24px -12px rgba(0,0,0,0.6)'
    : '0 1px 2px rgba(15,23,42,0.06), 0 4px 16px -6px rgba(15,23,42,0.12)';
  return {
    home: { gap: 28 },
    // ---- boas-vindas + números
    hero: {
      display: 'grid',
      gridTemplateColumns: 'minmax(340px, 1.15fr) 2fr',
      gap: 14,
      padding: 16,
      borderRadius: radius.lg,
      border: `1px solid ${c.border}`,
      background: c.bgCard,
      boxShadow: sombra,
      [theme.breakpoints.down('md')]: { gridTemplateColumns: 'minmax(0, 1fr)' },
    },
    boasVindas: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      padding: '22px 24px 20px',
      overflow: 'hidden',
      borderRadius: radius.md,
      border: `1px solid ${brand.limeBorder}`,
      background: `radial-gradient(120% 90% at 0% 0%, rgba(68,168,68,0.22) 0%, rgba(68,168,68,0) 55%), linear-gradient(160deg, ${c.bgSurface} 0%, ${c.bgCard} 100%)`,
      '& > *': { position: 'relative', zIndex: 1 },
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: 0,
        pointerEvents: 'none',
        backgroundImage: `radial-gradient(${
          escuro ? 'rgba(255,255,255,0.07)' : 'rgba(15,23,42,0.08)'
        } 1px, transparent 1px)`,
        backgroundSize: '16px 16px',
        maskImage: 'linear-gradient(135deg, transparent 35%, #000 100%)',
        WebkitMaskImage: 'linear-gradient(135deg, transparent 35%, #000 100%)',
      },
    },
    boasVindasEyebrow: {
      fontSize: '0.72rem',
      fontWeight: 700,
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      color: verde,
    },
    boasVindasTitulo: {
      margin: '10px 0 8px',
      fontSize: 'clamp(1.5rem, 2.1vw, 2rem)',
      fontWeight: 800,
      lineHeight: 1.15,
      letterSpacing: '-0.03em',
      color: c.textPrimary,
    },
    nome: { color: verde },
    boasVindasTexto: {
      margin: 0,
      fontSize: '0.9rem',
      lineHeight: 1.45,
      color: c.textSecondary,
    },
    pergunta: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      marginTop: 18,
      padding: '5px 5px 5px 16px',
      borderRadius: radius.pill,
      border: `1px solid ${c.borderLight}`,
      background: c.bgSurface,
      '&:focus-within': {
        borderColor: brand.lime,
        boxShadow: `0 0 0 3px ${brand.limeBg}`,
      },
      '& input': {
        flex: 1,
        minWidth: 0,
        padding: '9px 0',
        border: 0,
        outline: 0,
        background: 'transparent',
        color: c.textPrimary,
        font: 'inherit',
        fontSize: '0.9rem',
      },
    },
    time: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      flexWrap: 'wrap',
      marginTop: 18,
      paddingTop: 16,
      borderTop: `1px solid ${c.border}`,
    },
    rotulo: {
      fontSize: '0.7rem',
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      color: c.textMuted,
    },
    seletorTime: {
      appearance: 'none',
      padding: '6px 34px 6px 14px',
      borderRadius: radius.pill,
      border: `1px solid ${brand.limeBorder}`,
      backgroundColor: brand.limeBg,
      backgroundImage:
        "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%2344A844' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E\")",
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'right 12px center',
      color: c.textPrimary,
      font: 'inherit',
      fontSize: '0.86rem',
      fontWeight: 700,
      cursor: 'pointer',
      '&:focus-visible': {
        outline: `2px solid ${brand.lime}`,
        outlineOffset: 2,
      },
      '& option': { color: '#0f172a' },
    },
    champion: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 8,
      fontSize: '0.82rem',
      color: c.textSecondary,
      '& strong': { fontWeight: 600, color: c.textPrimary },
    },
    avatarPequeno: {
      width: 26,
      height: 26,
      fontSize: '0.64rem',
      fontWeight: 800,
      background: brand.limeBg,
      color: verde,
    },
    // ---- blocos de números
    blocos: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      gap: 12,
      '@media (max-width: 1250px)': {
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      },
      [theme.breakpoints.down('xs')]: { gridTemplateColumns: 'minmax(0, 1fr)' },
    },
    bloco: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      padding: '8px 20px',
      borderRadius: radius.md,
      border: `1px solid ${c.border}`,
      background: c.bgCard,
    },
    blocoVerde: {
      background: 'linear-gradient(135deg, #2e7d32 0%, #389338 100%)',
      borderColor: '#389338',
      '& $numeroRotulo, & $numeroValor': { color: '#fff' },
      '& $numeroSub': { color: 'rgba(255,255,255,0.85)' },
      '& $numero + $numero': { borderTopColor: 'rgba(255,255,255,0.2)' },
      '& $numeroIcone': { background: 'rgba(255,255,255,0.18)', color: '#fff' },
      '& $numero:hover $numeroRotulo': {
        color: '#fff',
        textDecoration: 'underline',
      },
    },
    numero: {
      display: 'flex',
      alignItems: 'center',
      gap: 14,
      padding: '13px 0',
      color: 'inherit',
      textDecoration: 'none',
      '& + $numero': { borderTop: `1px solid ${c.border}` },
      '&:hover': { textDecoration: 'none' },
      '&:hover $numeroRotulo': { color: verde },
    },
    numeroIcone: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: 34,
      height: 34,
      flexShrink: 0,
      borderRadius: 10,
      background: c.bgPill,
      color: c.textSecondary,
    },
    numeroTexto: {
      flex: 1,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
    },
    numeroRotulo: { fontSize: '0.9rem', fontWeight: 600, color: c.textPrimary },
    numeroSub: { fontSize: '0.75rem', color: c.textSecondary },
    numeroValor: {
      fontSize: '1.75rem',
      fontWeight: 800,
      letterSpacing: '-0.03em',
      color: c.textPrimary,
      fontVariantNumeric: 'tabular-nums',
    },
    esqueleto: {
      display: 'inline-block',
      width: 36,
      height: 26,
      borderRadius: 8,
      background: c.bgPill,
    },
    // ---- painéis
    painel: { boxShadow: sombra },
    painelTopo: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 16,
      flexWrap: 'wrap',
    },
    painelTitulo: {
      margin: 0,
      fontSize: '1.15rem',
      fontWeight: 800,
      letterSpacing: '-0.02em',
      color: c.textPrimary,
      '&::before': {
        content: '""',
        display: 'inline-block',
        width: 4,
        height: '1em',
        marginRight: 10,
        borderRadius: 3,
        background: brand.lime,
        verticalAlign: '-0.12em',
      },
    },
    painelSub: {
      margin: '2px 0 0',
      fontSize: '0.82rem',
      color: c.textSecondary,
    },
    painelFerramentas: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      flexWrap: 'nowrap',
      minWidth: 0,
      '& label': { flex: '0 1 240px', width: 240, minWidth: 160 },
      [theme.breakpoints.down('sm')]: {
        flexWrap: 'wrap',
        '& label': { flexBasis: '100%', width: '100%' },
      },
    },
    painelFiltros: {
      display: 'flex',
      alignItems: 'flex-end',
      gap: 10,
      flexWrap: 'wrap',
    },
    rolagem: { maxHeight: 400, overflowY: 'auto' },
    projeto: { display: 'flex', alignItems: 'center', gap: 12 },
    projetoAvatar: {
      width: 36,
      height: 36,
      borderRadius: 10,
      fontSize: '0.8rem',
      fontWeight: 800,
      background: brand.limeBg,
      color: verde,
    },
    projetoNome: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      fontWeight: 700,
      color: c.textPrimary,
    },
    projetoSigla: {
      display: 'block',
      fontSize: '0.74rem',
      letterSpacing: '0.04em',
      color: c.textMuted,
    },
    rodapePainel: { display: 'flex', justifyContent: 'flex-end' },
    divisao: {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 2fr) minmax(0, 1fr)',
      gap: 20,
      alignItems: 'start',
      [theme.breakpoints.down('md')]: { gridTemplateColumns: 'minmax(0, 1fr)' },
    },
    divisaoIgual: { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    appNome: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 10,
      fontWeight: 700,
      color: c.textPrimary,
      textDecoration: 'none',
      '&:hover': { color: verde },
    },
    appSigla: {
      minWidth: 28,
      padding: '2px 6px',
      borderRadius: 6,
      textAlign: 'center',
      fontSize: '0.7rem',
      fontWeight: 800,
      background: brand.limeBg,
      color: verde,
    },
    transacao: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      padding: '11px 0',
      color: 'inherit',
      textDecoration: 'none',
      borderBottom: `1px solid ${c.border}`,
      '&:last-child': { borderBottom: 0 },
      '&:hover': { textDecoration: 'none' },
      '&:hover $transacaoNome': { color: verde },
    },
    transacaoNome: {
      display: 'block',
      fontSize: '0.86rem',
      fontWeight: 600,
      color: c.textPrimary,
      overflowWrap: 'anywhere',
    },
    transacaoMeta: {
      display: 'block',
      fontSize: '0.74rem',
      color: c.textSecondary,
    },
    lista: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      maxHeight: 320,
      overflowY: 'auto',
    },
    novidade: {
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      padding: '10px 12px',
      borderRadius: radius.md,
      border: `1px solid ${c.border}`,
      background: c.bgSurface,
      '&:hover': { borderColor: brand.limeBorder },
    },
    novidadeTexto: {
      fontSize: '0.82rem',
      fontWeight: 500,
      lineHeight: 1.45,
      color: c.textPrimary,
    },
    emBreve: {
      borderStyle: 'dashed',
      borderColor: c.borderLight,
      background: 'transparent',
    },
    emBreveItem: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      padding: '10px 0',
      borderBottom: `1px solid ${c.border}`,
      '&:last-child': { borderBottom: 0 },
    },
    emBreveNome: { fontSize: '0.88rem', fontWeight: 600, color: c.textPrimary },
    emBreveTexto: { fontSize: '0.78rem', color: c.textSecondary },
    links: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
      padding: '4px 0 8px',
    },
  };
});

/** Estilos comuns do Atlas + os da Home. */
export function useStyles() {
  return { ...useAtlasStyles(), ...useHomeStyles() };
}
