apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.squad | replace("group:default/", "") }}-${{ values.nome }}-${{ values.ambiente }}
  description: Tópico SNS provisionado pelo Atlas
  annotations:
    atlas.nuclea.com.br/recurso: sns
    atlas.nuclea.com.br/ambiente: ${{ values.ambiente }}
  tags:
    - aws
    - sns
    - ${{ values.ambiente }}
spec:
  type: sns
  owner: ${{ values.squad }}
  system: infraestrutura
